/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Site;
import classes.Usuario;
import javax.swing.JOptionPane;
import repositorio.RepUsuario;
import repositorio.RepFornecedor;
import repositorio.RepCursos;
/**
 *
 * @author Alexsandra
 */
public class SiteInformações extends javax.swing.JInternalFrame {
    RepFornecedor repFornecedor = new RepFornecedor();
    RepUsuario repUsuario = new RepUsuario();
    RepCursos repCurso = new RepCursos();
    /**
     * Creates new form SiteInformações
     */
    public SiteInformações() {
        initComponents();
        
          jTextFieldUsuarioscadastrados.setText(
            String.valueOf(
            repUsuario.TotalDeUsuarios()
            ));
    
          jTextFieldFornecedorescadastrados.setText(
            String.valueOf(
            repFornecedor.TotalDeFornecedores()
            ));
          jTextFieldCursoscadastrados.setText(
            String.valueOf(
            repCurso.TotalDeCursos()
            ));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPaneHOMEPrincipal = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldUsuarioscadastrados = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCursoscadastrados = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldFornecedorescadastrados = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);

        jDesktopPaneHOMEPrincipal.setBackground(new java.awt.Color(153, 153, 153));

        jLabel2.setText("Direitos Autorais pertencentes a C.O.D.E., 2022.");

        jTextFieldUsuarioscadastrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioscadastradosActionPerformed(evt);
            }
        });

        jLabel1.setText("Total de Usuarios Cadastrados :");

        jTextFieldCursoscadastrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCursoscadastradosActionPerformed(evt);
            }
        });

        jLabel3.setText("Total de Cursos Inseridos :");

        jTextFieldFornecedorescadastrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFornecedorescadastradosActionPerformed(evt);
            }
        });

        jLabel4.setText("Total de Fornecedores  :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldUsuarioscadastrados, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldFornecedorescadastrados))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldCursoscadastrados, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUsuarioscadastrados, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFornecedorescadastrados, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCursoscadastrados, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jDesktopPaneHOMEPrincipal.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneHOMEPrincipal.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPaneHOMEPrincipalLayout = new javax.swing.GroupLayout(jDesktopPaneHOMEPrincipal);
        jDesktopPaneHOMEPrincipal.setLayout(jDesktopPaneHOMEPrincipalLayout);
        jDesktopPaneHOMEPrincipalLayout.setHorizontalGroup(
            jDesktopPaneHOMEPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneHOMEPrincipalLayout.createSequentialGroup()
                .addGroup(jDesktopPaneHOMEPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPaneHOMEPrincipalLayout.createSequentialGroup()
                        .addGap(21, 142, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(jDesktopPaneHOMEPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jDesktopPaneHOMEPrincipalLayout.setVerticalGroup(
            jDesktopPaneHOMEPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneHOMEPrincipalLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneHOMEPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneHOMEPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUsuarioscadastradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioscadastradosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioscadastradosActionPerformed

    private void jTextFieldFornecedorescadastradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFornecedorescadastradosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFornecedorescadastradosActionPerformed

    private void jTextFieldCursoscadastradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCursoscadastradosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCursoscadastradosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPaneHOMEPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldCursoscadastrados;
    private javax.swing.JTextField jTextFieldFornecedorescadastrados;
    private javax.swing.JTextField jTextFieldUsuarioscadastrados;
    // End of variables declaration//GEN-END:variables
}
